Repository UnnikrishnanBhargavakurup/hellocoop, pull requests merged in 2024-12, with the labels that each got.

#4 Improve GHA workflows
  .github/dependabot.yml
  .github/workflows/php-tests.yml
Labels: enhancement

#13 Fix: Ensure cookieToken in auth response reflects saved auth cookie
  src/Lib/Auth.php
  tests/Lib/AuthTest.php
Labels: bug

#15 Fix button visibility for `Continue with Hellō` and `Logout` based on authentication state.
  example/index.php
Labels: bug

#17 Fix lint issues in Config.
  composer.json
  src/Config/ConfigInterface.php
  src/Config/Constants.php
  src/Config/HelloConfig.php
  src/Config/HelloConfigBuilder.php
  src/Exception/CallbackException.php
  src/Exception/CryptoFailedException.php
  src/Exception/DecryptionFailedException.php
  src/Exception/InvalidSecretException.php
  src/Exception/NotImplementedException.php
  src/Exception/SameSiteCallbackException.php
  src/Handler/Auth.php
  src/Handler/Callback.php
  src/Handler/Invite.php
  src/Handler/Login.php
  src/HelloClient.php
  src/HelloRequest/HelloRequest.php
  src/HelloRequest/HelloRequestInterface.php
  src/HelloResponse/HelloResponse.php
  src/HelloResponse/HelloResponseInterface.php
  src/Lib/AuthHelper.php
  src/Lib/Crypto.php
  src/Lib/OIDCManager.php
  src/Lib/PKCE.php
  src/Lib/TokenFetcher.php
  src/Lib/TokenParser.php
  src/Renderers/DefaultPageRenderer.php
  src/Renderers/PageRendererInterface.php
  src/Type/Auth.php
  src/Type/AuthCookie.php
  src/Type/AuthUpdates.php
  src/Type/Claims.php
  src/Type/Common/OptionalAccountClaimsTrait.php
  src/Type/Common/OptionalOrgClaimTrait.php
  src/Type/Common/OptionalStringClaimsTrait.php
  src/Type/OIDC.php
  src/Utils/CurlWrapper.php
  src/Utils/HelloString.php
  src/Utils/QueryParamFetcher.php
Labels: Work In Progress
